name: Mobile Waldo Subscribers
on: 
  workflow_dispatch:
    inputs:
      email:
        type: string
  repository_dispatch:
permissions:
  actions: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Test Greeting
        run: echo "Waldo has successfully triggered this workflow"

      - name: Print email
        run: echo "the email is ${{ github.event.client_payload.email }}"