name: Mobile Waldo Subscribers
on: 
  push:
  workflow_dispatch:
  repository_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Test Greeting
        run: echo "hello nena"