name: Mobile Waldo Subscribers
on: 
  workflow_dispatch:
  repository_dispatch:
    types: [create_sub]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Test Greeting
        run: echo "Waldo has successfully triggered this workflow"

      - name: Print email
        run: echo "the email is ${{ github.event.client_payload.username }}"